### PR TITLE
Fix incorrect selection of punycode option

### PR DESCRIPTION
**Pull request by frdmn**
(related to #26)

### CODE REVIEW

**Comment by frdmn** [comment]
I noticed that the new added option to enable/disable punycode translation by `node-whois` doesn't work properly. Here are three WireShark screenshots:

|`whois` CLI (as exemplary request)|node-whois + `punycode: true`|node-whois + `punycode: false`|
|---|---|---|
||||

**Comment by hjr265** [comment]
@frdmn Thank you for the pull request, but this may break some existing functionality.

As you can see here: https://github.com/hjr265/node-whois/blob/master/servers.json#L408-L412 .. The `servers.json` file can also specify when to use punycode and when to not use it. Not looking into that property of server means we will be at least breaking node-whois for .de domains. 

My initial idea was to make punycode toggleable from servers.json. But I suppose there is a need to be able to override it form within code. If that is the case, then I suppose we need to do something like what you are suggesting here. But we need to make sure existing functionality doesn't break. Otherwise if we can just update servers.json that would be better.

Let me know your thoughts.

**Comment by frdmn** [comment]
Ah, I understand. 

My problem is that I need to permanently set punycode to `false` because I'm using a custom whois server (for any TLD lookups, not only .de) which does the punycode translation on their end. If I lookup the IDN-case, it will return an error. 

So I need to somehow disable the punycode without adjusting the `servers.json` file.

Any ideas how to solve this?

**Comment by hjr265** [comment]
Oh. I see. That makes sense.

So why not honor both? Let's make options.punycode a priority. If it is set to false, we always skip conversion in our package. But if it is not set to false, then we look at server.punycode and honor that. If even that is not set to false, we convert within package. Please let me know if that sounds good to you.

And would you be willing to update this pull request this way then? I will merge immediately after you do.

**Comment by frdmn** [comment]
@hjr265 I was about to update but for some reason I can not ever find `punycode` as element inside `server` object. Even for the `.de` domains. 

Would you mind helping me out?

**Comment by hjr265** [comment]
@frdmn Sure! I will take a look at this asap.

**Comment by frdmn** [comment]
Thanks a lot! 👌

Von meinem iPhone gesendet

**Comment by hjr265** [comment]
@frdmn I have pushed my change to this branch: https://github.com/hjr265/node-whois/commits/frdmn-master

Can you please try this and let me know if this works for you?

**Comment by frdmn** [comment]
@hjr265 Works like a charm! 👍

**Comment by hjr265** [comment]
@frdmn I have merged it with master and published it to npmjs.org as whois v2.2.0

**Pull request merged**
