### PR TITLE
Support for IPv6

### PR DESCRIPTION
**Pull request by kolonist**
A few changes to allow IPv6 addresses lookup.

#34

### CODE REVIEW

**Comment by hjr265** [comment]
@kolonist Thanks for this. I will take a look at it and merge it asap.

**Comment by ffoodd** [comment]
Hi there!
Could you please publish  latest versions on npm? I's stuck to 2.1.3, and this PR goes to 2.3.4.

I'm facing an "IPv6 not supported" error and this PR seems to fix it :)

Thanks a lot!

**Comment by hjr265** [comment]
Hi @ffoodd 

You are probably looking at the old package on npm. This is the one you want: https://www.npmjs.com/package/whois :smile: 

Hope that helps.

**Comment by ffoodd** [comment]
Indeed, thanks! And sorry I missed this XD

**Pull request merged**
